---
# This file contains all repeating variables, that can be set
# globaly instead of parse Zuul inventory file to get proper value.
#### GLOBAL VARS ####
ansible_user_dir: "{{ lookup('env', 'HOME') }}"
cifmw_project_dir: src/github.com/openstack-k8s-operators/ci-framework
cifmw_project_dir_absolute: "{{ ansible_user_dir }}/{{ cifmw_project_dir }}"
