---
- name: "Run ci/playbooks/molecule-test.yml"
  hosts: "{{ cifmw_zuul_target_host | default('controller') }}"
  gather_facts: false
  tasks:
    - name: Gather required facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "user_dir"
          - "env"

    - name: Load environment var if instructed to
      when:
        - cifmw_reproducer_molecule_env_file is defined
      ansible.builtin.include_vars:
        file: "{{ cifmw_reproducer_molecule_env_file }}"

    - name: Check if group_vars dir exists
      ansible.builtin.stat:
        path: "{{ zuul.project.src_dir }}/group_vars"
      register: group_vars_dir

    - name: Create group_vars dir if does not exist
      ansible.builtin.file:
        path: "{{ zuul.project.src_dir }}/group_vars"
        state: directory
        owner: zuul
        group: zuul
        mode: '0755'
      when: not group_vars_dir.stat.exists

    - name: Run molecule
      environment:
        ANSIBLE_LOG_PATH: "{{ ansible_user_dir }}/zuul-output/logs/ansible-execution.log"
        ANSIBLE_CALLBACKS_ENABLED: "ansible.posix.profile_tasks,yaml"
        MOLECULE_REPORT: "/tmp/report.html"
        LC_ALL: en_US.utf8
        LANG: en_US.utf8
        PATH: >-
          {{
            (
              [
                ansible_user_dir,
                'test-python',
                'bin'
              ] | ansible.builtin.path_join
            ) +
             ":" +
            (
              ansible_env.PATH |
              default('') |
              trim(":")
            )
          }}
      ansible.builtin.shell:
        chdir: "{{ roles_dir }}"
        cmd: >-
          set -o pipefail;
          molecule -c {{ mol_config_dir }} test --all |
          tee {{ ansible_user_dir }}/ci-framework-data/logs/molecule-execution.log
