---
# Mainly used to override the defaults set in .config/molecule/
# By default, it uses the "config_podman.yml" - in CI, it will use
# "config_local.yml".
log: true

provisioner:
  inventory:
    link:
      group_vars: ../../../../group_vars/
  name: ansible
  log: true
