---
- name: Export configuration for ceph client
  ansible.builtin.import_role:
    name: cifmw_ceph_client

- name: Output usage
  ansible.builtin.debug:
    msg: >-
      Import ceph secret into k8s
      'kubectl create -f /tmp/k8s_ceph_secret.yml'
