---
- name: Set cifmw_num_osds_perhost
# By defualt 1 OSD is created per node in case of multinode.
# 3 OSDS will be created for single node env to accomodate
# more ceph resources and avoid PG errors.
  ansible.builtin.set_fact:
    cifmw_num_osds_perhost: |
      {% if groups[cifmw_ceph_target | default('computes')] | length == 1 %}
      {% set num_osds =  3 %}
      {% else %}
      {% set num_osds = 1 %}
      {% endif %}
      {{ num_osds }}
- name: Create Block Device on EDPM Nodes
  vars:
    _target_group: "{{ cifmw_ceph_target | default('computes') }}"
    _target: "{{ groups[_target_group] | default([]) | first }}"
    ansible_ssh_private_key_file: >-
      {{
        hostvars[_target]['ansible_ssh_private_key_file'] |
        default(lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY'))
      }}
    cifmw_block_device_image_file: /var/lib/ceph-osd-{{ i }}.img
    cifmw_block_device_loop: /dev/loop{{ i + 3 }}
    cifmw_block_lv_name: ceph_lv{{ i }}
    cifmw_block_vg_name: ceph_vg{{ i }}
    cifmw_block_systemd_unit_file: /etc/systemd/system/ceph-osd-losetup-{{ i }}.service
  ansible.builtin.include_role:
    name: cifmw_block_device
  loop_control:
    loop_var: i
  loop: "{{ range(0, cifmw_num_osds_perhost|int) }}"
