---
- name: Get local private key
  ansible.builtin.slurp:
    src: "{{ lookup('env', 'HOME') }}/.ssh/{{ cifmw_admin_user }}-id_rsa"
  register: private_key_get
  delegate_to: localhost
  run_once: true
  no_log: true

- name: Get local public key
  ansible.builtin.slurp:
    src: "{{ lookup('env', 'HOME') }}/.ssh/{{ cifmw_admin_user }}-id_rsa.pub"
  register: public_key_get
  run_once: true
  delegate_to: localhost

- name: Import cifmw_create_admin role
  vars:
    cifmw_admin_user: ceph-admin
    cifmw_admin_pubkey: "{{ public_key_get['content'] | b64decode }}"
    cifmw_admin_prikey: "{{ private_key_get['content'] | b64decode }}"
    cifmw_admin_distribute_private_key: true
  ansible.builtin.import_role:
    name: cifmw_create_admin
  no_log: true
